version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    networks:
      - chatbot_net

  frontend:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - chatbot_net

networks:
  chatbot_net:
